### ISSUE TITLE
Long array having id 62 instead of 12?

### ISSUE THREAD

**Issue by NathanFallet** [Darkhax/OpenNBT#2]
I was reading the code and I saw the LongArrayTag is mapped with ID 62 instead of 12 as specified in the NBT specification. (see https://wiki.vg/NBT)

https://github.com/Darkhax/OpenNBT/blob/b1fe46640bf8c9f301d06428b8773f62f829fbfb/src/main/java/net/darkhax/opennbt/tags/TagRegistry.java#L43

**Comment by Darkhax** [comment]
The tag IDs 60+ in this library are not part of the official NBT spec. It looks like long arrays are a new feature added by Mojang.

**Comment by NathanFallet** [comment]
So you can update the id to support the new tag from newer nbt files, and maybe add something to remap 62 to 12 for existing files created with this lib
